# ************************************************************************
# Product    : Home information and control
# Date       : 2017-02-10
# Copyright  : Copyright (C) 2016-2017 Kjeholt Engineering. All rights reserved.
# Contact    : dev@kjeholt.se
# Url        : http://www-dev.kjeholt.se
# Licence    : ---
# -------------------------------------------------------------------------
# File       : mqtt-agent-tellstick/Dockerfile-rpi
# Version    : 1.1.0
# Author     : Bjorn Kjeholt
# *************************************************************************
 
FROM bkjeholt/base-nodejs-tellstick:dev-rpi

ARG DOCKER_IMAGE_NAME
ARG DOCKER_IMAGE_TAG

ENV DOCKER_IMAGE_NAME ${DOCKER_IMAGE_NAME:-UnknownName}
ENV DOCKER_IMAGE_TAG ${DOCKER_IMAGE_TAG:-UnknownRevision}
